/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocasaempeños;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.TableModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author grete
 */
public class IngresoEmpeños extends javax.swing.JFrame {
    
    ArrayList Lista = new ArrayList();
  //  DefaultListModel modelo= new DefaultListModel();
    String Identidad,Nombre,Apellido,NombreArticulo,cant,monto;
    int Cantidad;
    int id_cliente,id_estado,monto_acordado,id_producto;
    Double MontoAcordado;
    Validaciones valida = new Validaciones();
    Conexion con = new Conexion ();
    private static Connection conn;
    private static Statement stm;
    private static ResultSet rss;
    
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/bdd_poo";
    
    /**
     * Creates new form IngresoEmpeños
     */
     String[] rellenarDatosCliente = new String[3];
    public IngresoEmpeños() {
        initComponents();
        Consulta();
        con.comboestado(cbestado);
        this.DeshabilitarCopyPaste();
        compartirdatoscliente datoscliente = new compartirdatoscliente();
        Consultacliente();

        
        
    }
    
    private void compartirdatos()
    {
        compartirdatoscliente compartir = new compartirdatoscliente();
        this.Identidad=compartirdatoscliente.id;
        this.Nombre=compartirdatoscliente.nombre;
        this.Apellido=compartirdatoscliente.apellido;
        
    }
    
      private void DeshabilitarCopyPaste()
    {
        this.txtid.setTransferHandler(null);
        this.txtnombre.setTransferHandler(null);
        this.txtapellido.setTransferHandler(null);
        this.txtcorreo.setTransferHandler(null);
        this.txttelefono.setTransferHandler(null);
        this.txtdireccion.setTransferHandler(null);
        this.txtnombrearticulo.setTransferHandler(null);
        this.txtcantidad.setTransferHandler(null);
        this.txtmonto.setTransferHandler(null);
        
        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btningresarcliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnagregararticulo = new javax.swing.JButton();
        txtnombrearticulo = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbestado = new javax.swing.JComboBox<>();
        btnmostrarempeño = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaarticulo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listacliente = new javax.swing.JTable();
        btncontrato = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ingreso de Articulos a Empeñar");

        jLabel2.setText("Datos del Cliente");

        jLabel3.setText("Cliente:");

        jButton1.setText("Seleccionar cliente");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btningresarcliente.setText("Ingresar Cliente");
        btningresarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarclienteActionPerformed(evt);
            }
        });
        btningresarcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btningresarclienteKeyPressed(evt);
            }
        });

        jLabel4.setText("Identidad:");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre del cliente:");

        jLabel6.setText("Apellido del cliente:");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setText("Telefono");

        jLabel13.setText("Correo");

        jLabel14.setText("Direccion");

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });

        txtdireccion.setColumns(20);
        txtdireccion.setRows(5);
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtdireccion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btningresarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtapellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid)
                                    .addComponent(txtnombre))))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(txtcorreo))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btningresarcliente)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setText("Articulos a empeñar");

        jLabel8.setText("Nombre del articulo:");

        jLabel9.setText("Cantidad:");

        jLabel10.setText("Monto acordado:");

        btnagregararticulo.setText("Agregar articulo");
        btnagregararticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregararticuloActionPerformed(evt);
            }
        });
        btnagregararticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnagregararticuloKeyPressed(evt);
            }
        });

        txtnombrearticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrearticuloKeyTyped(evt);
            }
        });

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoKeyTyped(evt);
            }
        });

        jLabel11.setText("Estado");

        btnmostrarempeño.setText("Mostrar Empeños");
        btnmostrarempeño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarempeñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtmonto, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnombrearticulo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnagregararticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmostrarempeño, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnombrearticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmostrarempeño))
                .addGap(18, 18, 18)
                .addComponent(btnagregararticulo)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        listaarticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del articulo", "Cantidad", "Monto Total", "Estado"
            }
        ));
        listaarticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaarticuloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaarticulo);
        if (listaarticulo.getColumnModel().getColumnCount() > 0) {
            listaarticulo.getColumnModel().getColumn(0).setResizable(false);
            listaarticulo.getColumnModel().getColumn(1).setResizable(false);
            listaarticulo.getColumnModel().getColumn(2).setResizable(false);
            listaarticulo.getColumnModel().getColumn(3).setResizable(false);
        }

        listacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identidad", "Nombre", "Apellido", "Telefono", "Correo", "Dirreccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaclienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listacliente);
        if (listacliente.getColumnModel().getColumnCount() > 0) {
            listacliente.getColumnModel().getColumn(0).setResizable(false);
            listacliente.getColumnModel().getColumn(1).setResizable(false);
            listacliente.getColumnModel().getColumn(2).setResizable(false);
            listacliente.getColumnModel().getColumn(3).setResizable(false);
            listacliente.getColumnModel().getColumn(4).setResizable(false);
            listacliente.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btncontrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncontrato.setText("Ingresar Contrato");
        btncontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontratoActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncontrato)
                    .addComponent(btnregresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListaClientes listac=new ListaClientes();
        listac.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnagregararticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnagregararticuloKeyPressed
       
        
    }//GEN-LAST:event_btnagregararticuloKeyPressed

    private void btnagregararticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregararticuloActionPerformed
        // TODO add your handling code here:
        if(this.txtid.getText().trim().isEmpty()|| this.txtnombre.getText().trim().isEmpty() || this.txtapellido.getText().trim().isEmpty()||this.txttelefono.getText().trim().isEmpty() || this.txtcorreo.getText().trim().isEmpty() || this.txtdireccion.getText().trim().isEmpty()||this.txtnombrearticulo.getText().trim().isEmpty() || this.txtcantidad.getText().trim().isEmpty() || this.txtmonto.getText().trim().isEmpty() || String.valueOf(this.cbestado.getSelectedIndex()).equals("0"))
        {
            JOptionPane.showMessageDialog(null,"LLene todos los campos");
        }
        else
        {
            con.ingresararticulo(this.txtnombrearticulo.getText(),Integer.parseInt(txtcantidad.getText()),Integer.parseInt(txtmonto.getText()) ,this.cbestado.getSelectedIndex());
            this.valida.campoVacio(this.txtid);
            RefreshTable();
        }
       

    }//GEN-LAST:event_btnagregararticuloActionPerformed

    private void btningresarclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btningresarclienteKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btningresarclienteKeyPressed

    private void btningresarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarclienteActionPerformed
        // TODO add your handling code here:
        this.valida.campoVacio(this.txtid);
        if(this.txtid.getText().trim().isEmpty()|| this.txtnombre.getText().trim().isEmpty() || this.txtapellido.getText().trim().isEmpty()||this.txttelefono.getText().trim().isEmpty() || this.txtcorreo.getText().trim().isEmpty() || this.txtdireccion.getText().trim().isEmpty()||this.txtnombrearticulo.getText().trim().isEmpty() || this.txtcantidad.getText().trim().isEmpty() || this.txtmonto.getText().trim().isEmpty() || String.valueOf(this.cbestado.getSelectedIndex()).equals("0"))
        {
            JOptionPane.showMessageDialog(null,"LLene todos los campos");
        }
        else
        {
            con.ingresarcliente(this.txtid.getText(),this.txtnombre.getText(),this.txtapellido.getText(),this.txttelefono.getText(),this.txtcorreo.getText(),this.txtdireccion.getText());  
            this.valida.campoVacio(this.txtid);
            RefreshTable();
        }
       
    }//GEN-LAST:event_btningresarclienteActionPerformed

    private void btnmostrarempeñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarempeñoActionPerformed
        // TODO add your handling code here:
        MostrarEmpeños mostrarempeño = new MostrarEmpeños();
        mostrarempeño.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmostrarempeñoActionPerformed

    private void btncontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontratoActionPerformed
        // TODO add your handling code here:
        
        this.valida.campoVacio(this.txtid);
        if(this.txtid.getText().trim().isEmpty()|| this.txtnombre.getText().trim().isEmpty() || this.txtapellido.getText().trim().isEmpty()||this.txttelefono.getText().trim().isEmpty() || this.txtcorreo.getText().trim().isEmpty() || this.txtdireccion.getText().trim().isEmpty()||this.txtnombrearticulo.getText().trim().isEmpty() || this.txtcantidad.getText().trim().isEmpty() || this.txtmonto.getText().trim().isEmpty() || String.valueOf(this.cbestado.getSelectedIndex()).equals("0"))
        {
            JOptionPane.showMessageDialog(null,"LLene todos los campos");
        }
        else
        {
            //con.ingresarcliente(this.txtid.getText(),this.txtnombre.getText(),this.txtapellido.getText(),this.txttelefono.getText(),this.txtcorreo.getText(),this.txtdireccion.getText()); 
            //con.ingresararticulo(this.txtnombrearticulo.getText(),Integer.parseInt(txtcantidad.getText()),Integer.parseInt(txtmonto.getText()) ,this.cbestado.getSelectedIndex());
            this.obtenerdatosclientes(String.valueOf(this.txtid));
            this.obtenerproducto(this.NombreArticulo);
            this.obtenermonto(this.id_producto);
            
            con.ingresarcontrato(this.id_cliente,this.cbestado.getSelectedIndex(),this.monto_acordado);
            RefreshTable();
        }
            
        
    }//GEN-LAST:event_btncontratoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        valida.campoVacio(txtnombre);
        char caracter = evt.getKeyChar();
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        
        
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        valida.campoVacio(txtapellido);
        char caracter = evt.getKeyChar();
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        
        
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        char caracter = evt.getKeyChar();
        valida.campoVacio(txtcorreo);
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        char caracter = evt.getKeyChar();
        valida.campoVacio(txttelefono);
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        if(Character.isLetter(caracter))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar letras.");
            evt.consume();
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtnombrearticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrearticuloKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        char caracter = evt.getKeyChar();
        valida.campoVacio(txtnombrearticulo);
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        
    }//GEN-LAST:event_txtnombrearticuloKeyTyped

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        //valida.campoVacio(txtid);
        char caracter = evt.getKeyChar();
        valida.campoVacio(txtcantidad);
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        
        this.valida.campoVacio(txtid);
        if(Character.isLetter(caracter))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar letras.");
            evt.consume();
        }
        
        //char caracter = evt.getKeyChar();
        
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();
        valida.campoVacio(txtmonto);
        char caracter = evt.getKeyChar();
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;
        
        this.valida.campoVacio(txtid);
        if(Character.isLetter(caracter))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar letras.");
            evt.consume();
        }
        //char caracter = evt.getKeyChar();
        
    }//GEN-LAST:event_txtmontoKeyTyped

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();

        char caracter = evt.getKeyChar();
        if ((caracter == KeyEvent.VK_SPACE))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar espacios.");
            evt.consume();
        }
        int mensaje = 0;

        //char caracter = evt.getKeyChar();
        if(Character.isLetter(caracter))
        {
            JOptionPane.showMessageDialog(null, "No se pueden ingresar letras.");
            evt.consume();
        }

    }//GEN-LAST:event_txtidKeyTyped

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtidActionPerformed

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void listaclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaclienteMouseClicked
        // TODO add your handling code here:
       
        int seleccion = this.listacliente.rowAtPoint(evt.getPoint()); 
       // this.id_cliente = Integer.parseInt((String.valueOf(listacliente.getModel().getValueAt(seleccion, 0))));
        this.txtid.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 0))); 
        this.txtnombre.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 1)));
        this.txtapellido.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 2)));
        this.txttelefono.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 3)));
        this.txtcorreo.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 4)));
        this.txtdireccion.setText(String.valueOf(listacliente.getModel().getValueAt(seleccion, 5)));
       
        ///
    }//GEN-LAST:event_listaclienteMouseClicked

    private void listaarticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaarticuloMouseClicked
        // TODO add your handling code here:
       /* int seleccion = this.listaarticulo.rowAtPoint(evt.getPoint()); 
        this.id_producto = Integer.parseInt((String.valueOf(listaarticulo.getModel().getValueAt(seleccion, 0))));
        this.txtnombrearticulo.setText(String.valueOf(listaarticulo.getModel().getValueAt(seleccion, 1)));
        this.txtcantidad.setText(String.valueOf(listaarticulo.getModel().getValueAt(seleccion, 2)));
        this.txtmonto.setText(String.valueOf(listaarticulo.getModel().getValueAt(seleccion, 3)));
      */ 
        
    }//GEN-LAST:event_listaarticuloMouseClicked

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        Menu menu= new Menu();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpeños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpeños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpeños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpeños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoEmpeños().setVisible(true);
                Validaciones valida = new Validaciones();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregararticulo;
    private javax.swing.JButton btncontrato;
    private javax.swing.JButton btningresarcliente;
    private javax.swing.JButton btnmostrarempeño;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaarticulo;
    private javax.swing.JTable listacliente;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextArea txtdireccion;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtmonto;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnombrearticulo;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

public void Consulta()
    {
  
        try
        {
            conn = (Connection) DriverManager.getConnection(url, user, pass);
            DefaultTableModel model = new DefaultTableModel();
            stm = conn.createStatement();
            rss=stm.executeQuery("Select A.descripcion , A.cantidad_disponible, A.precio_referencial_venta , B.descripcion From inventario as A inner join estado as B on A.id_estado = B.id_estado where a.id_estado=1 order by id_producto desc LIMIT 5");
            
            model.addColumn("Nombre del Articulo");
            model.addColumn("Cantidad");
            model.addColumn("Monto Total");
            model.addColumn("Estado");
            //
            
            
            while(rss.next())
            {
              Object fila[] = new Object[4]; 
              
            for(int i =0;i<4;i++){
                fila[i]=rss.getObject(i+1);
            }
              model.addRow(fila);
            }
            this.listaarticulo.setModel(model);
        }        
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
            "Error de Conexion",JOptionPane.ERROR_MESSAGE);
        }   
     }
         public void RefreshTable(){
         this.listaarticulo.setModel(new DefaultTableModel());
         Consulta();
     }

        
    private void obtenerdatosclientes(String identidad){
         try
        {
            int obtener=0;
            
            conn = (Connection) DriverManager.getConnection(url, user, pass);
            stm = conn.createStatement();
            rss=stm.executeQuery("select id_cliente from clientes"+" WHERE identidad LIKE '%"+identidad+"%'");
            
            while(rss.next())
            {
                obtener=rss.getInt(1);
               
            }
            
           this.id_cliente=obtener;
            
            
       
        }        
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
            "Error de Conexion",JOptionPane.ERROR_MESSAGE);
        }   
     }
    
     private void obtenermonto(int id_producto){
         try
        {
            int obtener=0;
            
            conn = (Connection) DriverManager.getConnection(url, user, pass);
            stm = conn.createStatement();
            rss=stm.executeQuery("select precio_referencial_venta from inventario"+" WHERE id_producto LIKE '%"+this.id_producto+"%'");
            
            while(rss.next())
            {
                obtener=rss.getInt(1);
               
            }
            
           this.monto_acordado=obtener;
           
            
            
       
        }        
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
            "Error de Conexion",JOptionPane.ERROR_MESSAGE);
        }   
     }
     private void obtenerproducto(String id_producto){
         try
        {
            
            int obtener=0;
            
            conn = (Connection) DriverManager.getConnection(url, user, pass);
            stm = conn.createStatement();
            rss=stm.executeQuery("select id_producto from inventario"+" WHERE descripcion LIKE '%"+id_producto+"%'");
            
            while(rss.next())
            {
                obtener=rss.getInt(1);
               
            }
            
           this.id_producto=obtener;
            
            
       
        }        
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
            "Error de Conexion",JOptionPane.ERROR_MESSAGE);
        }   
     }
     
      public void Consultacliente()
    {
  
        try
        {
            conn = (Connection) DriverManager.getConnection(url, user, pass);
            DefaultTableModel model = new DefaultTableModel();
            stm = conn.createStatement();
            
            rss=stm.executeQuery("Select a.identidad, a.nombre , a.apellido,a.telefono , a.correo_electronico , a.direccion from clientes as a ");
           
            model.addColumn("Identidad");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Telefono");
            model.addColumn("Correo Electronico");
            model.addColumn("Direccion");
            
            
            while(rss.next())
            {
              Object fila[] = new Object[6];
              
            for(int i =0;i<6;i++){
                fila[i]=rss.getObject(i+1);
            }
              model.addRow(fila);
            }
            this.listacliente.setModel(model);
        }        
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
            "Error de Conexion",JOptionPane.ERROR_MESSAGE);
        }   
     }
            
     public void RefreshTable2(){
         this.listacliente.setModel(new DefaultTableModel());
         Consultacliente();
     }

}





