/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocasaempeños;

/**
 *
 * @author osegu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //this.pnlPrincipal.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnIngresarEmpeño = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnIngresarCompra = new javax.swing.JButton();
        btnIngresarVenta = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnPagarEmpeño = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        btnCerrarSesión = new javax.swing.JButton();
        btnIngresarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa de Empeños Gómez");
        setResizable(false);

        pnlPrincipal.setMinimumSize(new java.awt.Dimension(768, 384));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(768, 384));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarEmpeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/empeno.png"))); // NOI18N
        btnIngresarEmpeño.setText("Ingresar empeño");
        pnlPrincipal.add(btnIngresarEmpeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 248, -1));

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/empleado.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        pnlPrincipal.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 128, 248, -1));

        btnIngresarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/compra.png"))); // NOI18N
        btnIngresarCompra.setText("Ingresar compra");
        btnIngresarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCompraActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnIngresarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 250, 248, -1));

        btnIngresarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/venta.png"))); // NOI18N
        btnIngresarVenta.setText("Ingresar venta");
        pnlPrincipal.add(btnIngresarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 248, -1));

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/inventario.png"))); // NOI18N
        btnInventario.setText("Inventario");
        pnlPrincipal.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 248, -1));

        btnPagarEmpeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/pagar.png"))); // NOI18N
        btnPagarEmpeño.setText("Pagar empeño");
        pnlPrincipal.add(btnPagarEmpeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 128, 248, -1));

        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/reporte.png"))); // NOI18N
        btnGenerarReporte.setText("Generar reporte");
        pnlPrincipal.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 6, 248, -1));

        btnCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/salir.png"))); // NOI18N
        btnCerrarSesión.setText("Cerrar sesión");
        btnCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesiónActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 250, 248, -1));

        btnIngresarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocasaempeños/Imágenes/nuevo-usuario.png"))); // NOI18N
        btnIngresarCliente.setText("Ingresar cliente");
        pnlPrincipal.add(btnIngresarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 6, 248, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesiónActionPerformed

    private void btnIngresarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCompraActionPerformed
        
        this.dispose();
        
        IngresarCompras ingresarCompras = new IngresarCompras();
        
        ingresarCompras.setVisible(true);
    }//GEN-LAST:event_btnIngresarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesión;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnIngresarCliente;
    private javax.swing.JButton btnIngresarCompra;
    private javax.swing.JButton btnIngresarEmpeño;
    private javax.swing.JButton btnIngresarVenta;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPagarEmpeño;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
